Feature/loc 64
Localhost-305/localhost-backend pull request #33
Opened 2024-10-28 22:46 UTC by Daniloel

2024-10-29 22:41 UTC, laroyprado requested changes

2024-10-29 22:41 UTC, laroyprado commented on src/main/java/com/api/domain/dto/QuantityApplicationDto.java
Usar o Lombok para que seja feito a criação dos Get e Set, deixando código mais limpo

2024-10-29 22:58 UTC, LukasFernando commented on src/main/java/com/api/domain/service/QuantityApplicationsService.java
> +            averageAll = Math.round(averageAll * (1 - 0.5) * 100.0) / 100.0;
a parte "(1 - 0.5)" pode ser reduzida para "0.5", não tem a necessidade de fazer essa conta

2024-10-31 01:21 UTC, laroyprado approved these changes

2024-10-31 01:22 UTC, merged