Feature/LOC-11
Localhost-305/localhost-backend pull request #7
Opened 2024-09-25 00:55 UTC by Daniloel

2024-09-25 01:22 UTC, LukasFernando commented on src/main/java/com/api/domain/entity/Candidate.java
> -    @Column(name = "created_on") // use only to convert Camel Case (createdOn) to Snake Case (created_on)
nao vai ter mais esses campo?

2024-09-25 01:45 UTC, LucasOliveira321 requested changes

2024-09-25 01:45 UTC, LucasOliveira321 commented on src/main/java/com/api/controller/FactApplicationController.java
> +
Os parâmetros não estão opcionais;
O retorno sempre será ResponseEntity;

2024-09-25 01:45 UTC, LucasOliveira321 commented on src/main/java/com/api/domain/entity/Hour.java
>      private Integer hour;
Remover @Column(name = "hour"), não é necessário

2024-09-25 01:45 UTC, LucasOliveira321 commented on src/main/java/com/api/domain/repository/HourRepository.java
> +//}
Remover comentário

2024-09-25 01:45 UTC, LucasOliveira321 commented on src/main/java/com/api/domain/repository/HourRepository.java
> +
GetAllById (Pegar todos por ID)?? está confuso, por padrão o JPA possuí o getAll() e o getById()

2024-09-25 01:45 UTC, LucasOliveira321 commented on src/main/java/com/api/domain/repository/JobRepository.java
>  }
findAllByJobId (Buscar todos por ID)?? está confuso, por padrão o JPA possuí o getAll() e o getById()

2024-09-25 01:45 UTC, LucasOliveira321 commented on src/main/java/com/api/domain/repository/RecruiterRepository.java
>  }
findAllByRecruiterId (Buscar todos por ID)?? está confuso, por padrão o JPA possuí o getAll() e o getById()

2024-09-25 01:45 UTC, LucasOliveira321 commented on src/main/java/com/api/domain/service/FactApplicationService.java
> +
Retorno sempre por ResponseEntity

2024-09-25 03:55 UTC, Daniloel commented on src/main/java/com/api/domain/repository/HourRepository.java
> +
As tabelas do entity não  id, sendo assim vou adotar o getAll.

2024-09-25 03:55 UTC, Daniloel commented on src/main/java/com/api/domain/repository/JobRepository.java
>  }
As tabelas do entity não  id, sendo assim vou adotar o getAll.

2024-09-26 02:09 UTC, Daniloel commented on src/main/java/com/api/domain/entity/Candidate.java
> -    @Column(name = "created_on") // use only to convert Camel Case (createdOn) to Snake Case (created_on)
Não, foi pedido para remover

2024-09-26 02:09 UTC, Daniloel commented on src/main/java/com/api/domain/repository/HourRepository.java
> +//}
Removido

2024-09-26 02:17 UTC, Daniloel commented on src/main/java/com/api/domain/repository/JobRepository.java
>  }
Removido

2024-09-26 02:40 UTC, Daniloel commented on src/main/java/com/api/domain/service/FactApplicationService.java
> +
Realizada a alteração

2024-09-26 02:42 UTC, Daniloel reviewed
Realizadas as mudanças apontadas.

2024-09-27 00:33 UTC, LukasFernando approved these changes

2024-09-27 00:33 UTC, LukasFernando commented on src/main/java/com/api/controller/FactApplicationController.java
> +//    public ArrayList<Object> getAll(@RequestParam ("StartDate") String startDateStr , @RequestParam("EndDate") String endDateStr) {
Remova os comentarios de codigos

2024-09-27 23:11 UTC, LucasOliveira321 approved these changes

2024-09-27 23:11 UTC, merged